// Mock data from the Python script output
const mockData = {
    monthlySummary: {
        "2019-01": 754.90,
        "2018-02": 3550.98,
        "2018-01": 11947.49,
        "2017-12": 2378.43,
        "2017-11": 1200.65,
        "2018-03": 7760.10
    },
    spendingAnalytics: {
        spending_by_store: {
            "GARDENIA BAKERIES (KL) SDN BHD": 2419.80,
            "UNIHAKKA INTERNATIONAL SDN BHD": 1559.50
        },
        most_frequent_stores: [
            ["GARDENIA BAKERIES (KL) SDN BHD", 76],
            ["UNIHAKKA INTERNATIONAL SDN BHD", 69],
            ["SANYU STATIONERY SHOP", 49],
            ["99 SPEED MART S/B", 44],
            ["MR. D.I.Y. (M) SDN BHD", 41]
        ],
        average_transaction_value: 66.86
    },
    alerts: [
        "High Spending Alert: Spending in 2018-01 ($11947.49) was significantly higher than the average.",
        "High Spending Alert: Spending in 2018-03 ($7760.10) was significantly higher than the average.",
        "Large Transaction Alert: A transaction of $848.00 at KOH SENG HARDWARE on 2017-12-04 exceeded the threshold of $500."
    ]
};

function displayMonthlySummary(summary) {
    const container = document.getElementById('monthly-summary-data');
    let html = '<ul>';
    for (const [month, total] of Object.entries(summary)) {
        html += `<li><strong>${month}:</strong> $${total.toFixed(2)}</li>`;
    }
    html += '</ul>';
    container.innerHTML = html;
}

function displaySpendingAnalytics(analytics) {
    const container = document.getElementById('spending-analytics-data');
    let html = '<h3>Top 5 Most Frequent Stores</h3><ul>';
    analytics.most_frequent_stores.forEach(([store, count]) => {
        html += `<li>${store}: ${count} visits</li>`;
    });
    html += '</ul>';
    html += `<p><strong>Average Transaction Value:</strong> $${analytics.average_transaction_value.toFixed(2)}</p>`;
    container.innerHTML = html;
}

function displayAlerts(alerts) {
    const container = document.getElementById('alerts-data');
    let html = '<ul>';
    alerts.forEach(alert => {
        html += `<li>${alert}</li>`;
    });
    html += '</ul>';
    container.innerHTML = html;
}

function displayReportChart() {
    const chart = document.getElementById('report-chart');
    // The chart is a static image generated by the Python script
    chart.src = 'monthly_expense_summary.png';
}

document.addEventListener('DOMContentLoaded', () => {
    displayMonthlySummary(mockData.monthlySummary);
    displaySpendingAnalytics(mockData.spendingAnalytics);
    displayAlerts(mockData.alerts);
    displayReportChart();
});

